version: '3'
services:
  app:
    build:
      context: .
      args:
        rails_env: production
    volumes:
      - .:/code
    environment:
      - PASSENGER_PORT=3000
      - FORCE_SSL=${FORCE_SSL}
      - DATABASE_URL=postgres://postgres@postgres:5432/decidim_sabadell
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    ports:
      - $PORT:3000
    links:
      - postgres
      - redis
    command: ["./wait-for-postgres.sh", "postgres", "--", "./run-app.sh"]
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=decidim_sabadell
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis-data:/data
volumes:
  postgres-data: {}
  redis-data: {}

