version: '2'
services:
  app:
    build:
      context: .
      args:
        rails_env: production
    volumes:
      - .:/code
    environment:
      - FORCE_SSL=true
      - DATABASE_URL=postgres://postgres@pg:5432/decidim
      - SECRET_KEY_BASE=$SECRET_KEY_BASE
    ports:
      - 3000:3000
    links:
      - pg
      - redis
  pg:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USERNAME=postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis-data:/data
volumes:
  pg-data: {}
  redis-data: {}
