version: '3'
services:
  app:
    build:
      context: .
      args:
        rails_env: production
    volumes:
      - .:/code
    environment:
      - PASSENGER_PORT=3000
      - FORCE_SSL=${FORCE_SSL}
      - DATABASE_URL=postgres://postgres@pg:5432/decidim
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    ports:
      - $PORT:3000
    links:
      - pg
      - redis
  pg:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USERNAME=postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis-data:/data
volumes:
  pg-data: {}
  redis-data: {}

